name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Code to Server
      run: |
        ssh -o StrictHostKeyChecking=no deploy@170.64.157.229 << 'EOF'
          cd /var/www/ponglytics
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:clear
          php artisan cache:clear
          php artisan queue:restart
          sudo systemctl restart php8.3-fpm
          sudo systemctl reload nginx
        EOF
